BilenAdam.XITT.Admin.HotelCharter/Controllers/HotelPensionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using BilenAdam.Data.HotelData;
using BilenAdam.Utilities.Paging;
using System.Data.Linq;
using BilenAdam.XITT.Admin.HotelCharter.Models;


namespace BilenAdam.XITT.Admin.HotelCharter.Controllers
{
    public class HotelPensionController : Controller
    {
        public ActionResult Index(int pageIndex = 1, int pageSize = 10)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var data = db.HotelPensions.AsQueryable();

                var model = data.ToPagedList<HotelPension>(pageIndex, pageSize);
                return View(model);
            }
        }

      

      

       

        [HttpPost]
        public ActionResult Create(BilenAdam.Data.HotelData.HotelPension model)
        {
            try
            {
                using (var db = this.CreateHotelDataContext())
                {
                  
                    
                    db.HotelPensions.InsertOnSubmit(model);
                    db.SaveChanges(User.Identity.Name);
                }

                return this.Redirect2Action(s => s.Index(1, 10));
            }
            catch (Exception exc)
            {
                ModelState.AddModelError(string.Empty, exc.Message);
            }

            return this.Redirect2Action(s => s.Index(1, 10));
        }


       

        [HttpPost]
        public ActionResult Edit(BilenAdam.Data.HotelData.HotelPension model)
        {
            if (ModelState.IsValid)
            {
                using (var db = this.CreateHotelDataContext())
                {


                    var item = db.HotelPensions.FirstOrDefault(c => c.Id == model.Id);

                    if (item == null)
                        return HttpNotFound();

                    item.UpdateFrom(model,"xRes");
                    
                    db.SaveChanges(User.Identity.Name);

                }
                
            }
            return this.Redirect2Action(s => s.Index(1, 10));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = this.CreateHotelDataContext())
                {

                    db.HotelPensions.DeleteByIdOnSubmit(id);
                    db.SaveChanges(User.Identity.Name);
                }


            }
            catch (Exception exc)
            {
                ModelState.AddModelError(null, exc.Message);
            }
            return this.Redirect2Action(s => s.Index(1, 10));
        }
    }
}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelPension/CreatePartial.cshtml
@model  BilenAdam.Data.HotelData.HotelPension




    @using (Html.BeginForm("Create", "HotelPension", FormMethod.Post, new { @class="form-inline"}))
    {
       

       


        <div class="form-group">
          
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
          
       


                <!-- Button trigger modal -->
                <button type="button" class="btn" data-toggle="modal" data-target="#myModal">
                    <i class="fa fa-globe"></i>
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                            </div>
                            <div class="modal-body">

                                @Html.Partial("ResourceEditorPartial", PropertyResourceEditorModelUtils.Create(Model, m => m.Name, BilenAdam.Data.HotelData.Resources.EntityResources.name_display))
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
        
            </div>
       
     

       
          
        

        <button type="submit" class="btn btn-success">@BilenAdam.Resources.App.Crud.Save</button>

 
    }

BilenAdam.XITT.Admin.HotelCharter/Views/HotelPension/EditPartial.cshtml
@model  BilenAdam.Data.HotelData.HotelPension

@{
    ViewBag.Title = "Update";
}


@using (Html.BeginForm("Edit", "HotelPension", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)


    @Html.HiddenFor(o => o.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-3 control-label" })
        <div class="col-sm-9">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">

        @Html.Partial("ResourceEditorPartial", PropertyResourceEditorModelUtils.Create(Model, m => m.Name, BilenAdam.Data.HotelData.Resources.EntityResources.name_display))
    </div>
    <div class="form-group">
        

    </div>
    <div class="btn-group btn-group-justified">
        <div class="btn-group">
            <button type="submit" class="btn btn-primary">@BilenAdam.Resources.App.Crud.Save</button>
        </div>


    </div>

}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelPension/Index.cshtml
@model PagedList<HotelPension>

@{
    ViewBag.Title = "Index"; 
}

<div class="container card">
    <div class="card-body card-padding">


        <div class="row table-responsive">
            @Html.Partial("CreatePartial", new BilenAdam.Data.HotelData.HotelPension())
        </div>
        <div class="row table-responsive">
            <table class="table">
                <tr>
                    <th>
                        @EntityResources.id_display
                    </th>

                    <th>
                        @EntityResources.name_display
                    </th>

                    <th colspan="2">

                    </th>
                </tr>

                @foreach (var item in Model)
            {
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>


                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <button type="button" class="btn" data-toggle="modal" data-target="#myModal_@item.Id">
                            @BilenAdam.Resources.App.Crud.Edit
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="myModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                                    </div>
                                    <div class="modal-body">

                                        @Html.Partial("EditPartial", item)
                                    </div>
                                    <div class="modal-footer">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>
                        <a href="@Url.Action("Delete", new { Id = item.Id })" class="btn btn-link">
                            @BilenAdam.Resources.App.Crud.Delete
                        </a>
                    </td>
                </tr>
            </tbody>
            }
                <tfoot>
                    <tr>
                        <td colspan="4">
                            @Html.Pager(Model)
                        </td>
                    </tr>
                </tfoot>

            </table>
        </div>
    </div>
</div>