BilenAdam.XITT.Admin.HotelCharter/Controllers/HotelFareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using BilenAdam.Data.HotelData;
using BilenAdam.Utilities.Paging;

using System.Data.Linq;


namespace BilenAdam.XITT.Admin.HotelCharter.Controllers
{
    public class HotelFareController : Controller
    {
        public ActionResult HotelSearch(string name = null, string countryCode = null, int? cityId = null, int? districtId = null, int pageIndex = 1, int pageSize = 10)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var data = db.Hotels.AsQueryable();

                if (!string.IsNullOrEmpty(name))
                    data = data.Where(o => o.Name.Contains(name));

                if (!string.IsNullOrEmpty(countryCode))
                    data = data.Where(o => o.HotelDestination.CountryCode == countryCode);


                if (districtId != null && cityId != null)
                    data = data.Where(o => o.HotelDestination.Id == districtId && o.HotelDestination.ParentId == cityId);
                else if (cityId != null)
                    data = data.Where(o => o.HotelDestionationId == cityId);

                var model = data.ToPagedList<Hotel>(pageIndex, pageSize);
                return View(model);
            }
        }
        public ActionResult Index(int hotelSeasonId)
        {
            var db = this.CreateHotelDataContext();
            ViewData.SetDB(db);

           


            var season = db.HotelSeasons.FirstOrDefault(s => s.Id == hotelSeasonId);
            ViewData["HotelSeason"] = season;
            ViewData["PensionLists"] = db.HotelPensions.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name }).ToArray();

            return View(season);
        }




        [HttpGet]
        public ActionResult FareDetails(int hotelSeasonId, int pensionId)
        {
            var db = this.CreateHotelDataContext();
            ViewData.SetDB(db);

            var season = db.HotelSeasons.FirstOrDefault(s => s.Id == hotelSeasonId);
            ViewData["HotelSeason"] = season;

            Models.HotelFareDetailsModel model = new Models.HotelFareDetailsModel
            {
                HotelData = db.Hotels.FirstOrDefault(h => h.Id == season.HotelId),
                MarketData = db.HotelMarkets.FirstOrDefault(m => m.Id == season.HotelMarketId),
                PensionData = db.HotelPensions.FirstOrDefault(p => p.Id == pensionId),
                Headers = db.HotelFareHs.Where(h => h.HotelSeasonId == season.Id && h.IsSPOEnabled == null).OrderBy(h => h.BeginDate).ToList(),
                RoomGroups = new List<Models.HotelFareRoomGroupModel>()
            };


            foreach (var room in db.HotelRooms.Where(r => r.HotelId == season.HotelId))
            {
                Models.HotelFareRoomGroupModel roomModel = new Models.HotelFareRoomGroupModel
                {
                    RoomData = room,
                    DetailGroups = new List<Models.HotelFareDetailGroupModel>()
                };

                model.RoomGroups.Add(roomModel);
                foreach (var fareDetail in db.HotelFareDs.Where(r => r.RoomId == room.Id && r.PensionId == pensionId && r.HotelFareH.HotelSeasonId == hotelSeasonId && r.HotelFareH.IsSPOEnabled == null))
                {
                    var group = roomModel.DetailGroups.FirstOrDefault(g => g.Adults == fareDetail.Adults && g.Childs == fareDetail.Childs && g.FirstChildMinAge == (fareDetail.FirstChildMinAge ?? 0) && g.FirstChildMaxAge == (fareDetail.FirstChildMaxAge ?? 0) && g.SecondChildMinAge == (fareDetail.SecondChildMinAge ?? 0) && g.SecondChildMaxAge == (fareDetail.SecondChildMaxAge ?? 0) && g.ThirdChildMinAge == (fareDetail.ThirdChildMinAge ?? 0) && g.ThirdChildMaxAge == (fareDetail.ThirdChildMaxAge ?? 0) && g.FourthChildMinAge == (fareDetail.FourthChildMinAge ?? 0) && g.FourthChildMaxAge == (fareDetail.FourthChildMaxAge ?? 0));
                    if (group == null)
                    {
                        group = new Models.HotelFareDetailGroupModel
                        {
                            Adults = fareDetail.Adults,
                            Childs = fareDetail.Childs,
                            Details = model.Headers.Select(h => new Models.HotelFareHeaderDetailModel { FareHeader = h }).ToList(),
                            FirstChildMinAge = fareDetail.FirstChildMinAge ?? 0,
                            FirstChildMaxAge = fareDetail.FirstChildMaxAge ?? 0,
                            SecondChildMinAge = fareDetail.SecondChildMinAge ?? 0,
                            SecondChildMaxAge = fareDetail.SecondChildMaxAge ?? 0,
                            ThirdChildMinAge = fareDetail.ThirdChildMinAge ?? 0,
                            ThirdChildMaxAge = fareDetail.ThirdChildMaxAge ?? 0,
                            FourthChildMinAge = fareDetail.FourthChildMinAge ?? 0,
                            FourthChildMaxAge = fareDetail.FourthChildMaxAge ?? 0
                        };
                        roomModel.DetailGroups.Add(group);
                    }

                    group.Details.FirstOrDefault(d => d.FareHeader.Id == fareDetail.FareHId).FareDetail = fareDetail;
                }


            }

            return View(model);

        }


        [HttpPost]
        public ActionResult UpdateDetail(int fareid, decimal fare)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var detail = db.HotelFareDs.FirstOrDefault(i => i.Id == fareid);
                foreach (var item in db.HotelFareDs.Where(i =>  i.HotelFareH.SeasonCode == detail.HotelFareH.SeasonCode && i.HotelFareH.HotelSeasonId == detail.HotelFareH.HotelSeasonId && i.Adults == detail.Adults && i.Childs == detail.Childs))
                {
                    if (item.RoomId == detail.RoomId && item.FirstChildMaxAge == detail.FirstChildMaxAge && item.FirstChildMinAge == detail.FirstChildMinAge && item.SecondChildMaxAge == detail.SecondChildMaxAge && item.SecondChildMinAge == detail.SecondChildMinAge && item.ThirdChildMaxAge == detail.ThirdChildMaxAge && item.ThirdChildMinAge == detail.ThirdChildMinAge)
                    {
                        item.Fare = fare;
                    }
                }
                db.SaveChanges(User.Identity.Name);
            }

            return Content("OK");
        }

        [HttpPost]
        public ActionResult AddDetail(int seasonid, string seasoncode, int roomid, int pensionid, byte adults, byte childs, decimal fare, string childAges = null)
        {
            using (var db = this.CreateHotelDataContext())
            {
                byte[] childAgesArray = childAges.Split('-').Select(s => byte.Parse(s)).ToArray();
                foreach (var fareHeader in db.HotelFareHs.Where(h => h.HotelSeasonId == seasonid && h.SeasonCode == seasoncode))
                {


                    var hotelFareD = new HotelFareD
                    {
                        FareHId = fareHeader.Id,
                        RoomId = roomid,
                        PensionId = pensionid,
                        Adults = adults,
                        Childs = childs,
                        Fare = fare,
                        FirstChildMinAge = childs >= 1 ? childAgesArray[0] : (byte?)null,
                        FirstChildMaxAge = childs >= 1 ? childAgesArray[1] : (byte?)null,
                        SecondChildMinAge = childs >= 2 ? childAgesArray[2] : (byte?)null,
                        SecondChildMaxAge = childs >= 2 ? childAgesArray[3] : (byte?)null,
                        ThirdChildMinAge = childs >= 3 ? childAgesArray[4] : (byte?)null,
                        ThirdChildMaxAge = childs >= 3 ? childAgesArray[5] : (byte?)null,
                        FourthChildMinAge = childs >= 4 ? childAgesArray[6] : (byte?)null,
                        FourthChildMaxAge = childs >= 4 ? childAgesArray[7] : (byte?)null
                    };

                    db.HotelFareDs.Upsert(i =>
                    i.FareHId == hotelFareD.FareHId
                    && i.RoomId == hotelFareD.RoomId
                    && i.PensionId == hotelFareD.PensionId
                    && i.Adults == hotelFareD.Adults
                    && i.Childs == hotelFareD.Childs
                    && (childs < 1 || i.FirstChildMinAge == hotelFareD.FirstChildMinAge)
                    && (childs < 1 || i.FirstChildMaxAge == hotelFareD.FirstChildMaxAge)
                    && (childs < 2 || i.SecondChildMinAge == hotelFareD.SecondChildMinAge)
                    && (childs < 2 || i.SecondChildMaxAge == hotelFareD.SecondChildMaxAge)
                    && (childs < 3 || i.ThirdChildMinAge == hotelFareD.ThirdChildMinAge)
                    && (childs < 3 || i.ThirdChildMaxAge == hotelFareD.ThirdChildMaxAge)
                    && (childs < 4 || i.FourthChildMinAge == hotelFareD.FourthChildMinAge)
                    && (childs < 4 || i.FourthChildMaxAge == hotelFareD.FourthChildMaxAge)
                    , hotelFareD);
                }
                db.SaveChanges(User.Identity.Name);

                return Content("OK");
            }
        }

        [HttpPost]
        public ActionResult DeleteDetails(int hotelSeasonId, int pensionId, int roomid, byte adults, byte childs, string childAges = null)
        {
            byte[] childAgesArray = childAges == null ? null : childAges.Split('-').Select(s => byte.Parse(s)).ToArray();

            using (var db = this.CreateHotelDataContext())
            {
                var items = db.HotelFareDs.Where(d => d.HotelFareH.HotelSeasonId == hotelSeasonId && d.PensionId == pensionId && d.RoomId == roomid && d.Adults == adults && d.Childs == childs && d.HotelFareH.IsSPOEnabled == null

                  && (childs < 1 || d.FirstChildMinAge == childAgesArray[0])

BilenAdam.XITT.Admin.HotelCharter/Controllers/HotelSPOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using BilenAdam.Data.HotelData;
using BilenAdam.Utilities.Paging;

namespace BilenAdam.XITT.Admin.HotelCharter.Controllers
{
    public class HotelSPOController : Controller
    {
        public ActionResult Index(int hotelSeasonId)
        {
            var db = this.CreateHotelDataContext();
            ViewData.SetDB(db);
            ViewData["HotelSeason"] = db.HotelSeasons.FirstOrDefault(s => s.Id == hotelSeasonId);
            var model = db.HotelFareHs.Where(f => f.HotelSeasonId == hotelSeasonId && f.IsSPOEnabled != null).ToArray();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create(int hotelSeasonId)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var data = db.HotelSeasons.FirstOrDefault(s => s.Id == hotelSeasonId);

                var model = new HotelFareH { HotelId = data.HotelId, IsSPOEnabled = true, MarketId = data.HotelMarketId, HotelSeasonId = data.Id, SeasonCode = "SPO", Currency = "EUR" };
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Create(HotelFareH model)
        {
            using (var db = this.CreateHotelDataContext())
            {
                model.SeasonCode = "SPO";
                db.HotelFareHs.InsertOnSubmit(model);
                db.SaveChanges(User.Identity.Name);

                return RedirectToAction("Fares", new { Id = model.Id });
            }
        }


        [HttpGet]
        public ActionResult Delete(int Id, int hotelSeasonId)
        {
            using (var db = this.CreateHotelDataContext())
            {
                db.HotelFareHs.DeleteByIdOnSubmit(Id);
                db.SaveChanges(User.Identity.Name);
            }

            return RedirectToAction("Index", new { hotelSeasonId = hotelSeasonId });
        }


        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var db = this.CreateHotelDataContext();
            ViewData.SetDB(db);
            var model = db.HotelFareHs.FirstOrDefault(f => f.Id == Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(HotelFareH model)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var item = db.HotelFareHs.FirstOrDefault(f => f.Id == model.Id);
                item.UpdateFrom(model, "HotelId", "MarketId", "HotelSeasonId", "SeasonCode");
                db.SaveChanges(User.Identity.Name);
            }

            return RedirectToAction("Index", new { hotelSeasonId = model.HotelSeasonId });
        }


        [HttpGet]
        public ActionResult Fares(int Id, int? pensionId = null)
        {
            var db = this.CreateHotelDataContext();
          
            var spoHeader = db.HotelFareHs.FirstOrDefault(h => h.Id == Id);

            if(spoHeader == null)
            {
                db.Dispose();
                return HttpNotFound();
            }

            Models.HotelSPOFareDetails model = new Models.HotelSPOFareDetails
            {
                 Header = spoHeader
            };

            if (pensionId != null)
            {

                model.PensionData = db.HotelPensions.FirstOrDefault(p => p.Id == pensionId);

                model.RoomGroups = new List<Models.HotelSPOFareRoomGroup>();

                foreach (var room in spoHeader.Hotel.HotelRooms.OrderBy(r => r.Name))
                {
                   // Models.HotelSPOFareRoomGroup roomGroup = new Models.HotelSPOFareRoomGroup { RoomData = room, Details = spoHeader.HotelFareDs.Where(d => d.PensionId == pensionId).ToList() };
                    
                    model.RoomGroups.Add(new Models.HotelSPOFareRoomGroup { RoomData = room, Details = spoHeader.HotelFareDs.Where(d => d.PensionId == pensionId && d.RoomId == room.Id).ToList() });
                }
            }
           


            ViewData.SetDB(db);
            return View(model);

        }

        [HttpPost]
        public ActionResult AddDetail(int fareHeaderId, int roomId, int pensionid, decimal fare, byte adt, byte chd, byte chd1min, byte chd1max, byte chd2min, byte chd2max, byte chd3min, byte chd3max, byte chd4min, byte chd4max)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var newDetail = new BilenAdam.Data.HotelData.HotelFareD
                {
                     FareHId = fareHeaderId,
                     RoomId = roomId,
                     PensionId = pensionid,
                     Fare = fare,
                     Adults = adt,
                     Childs = chd
                };
                StringBuilder fareText = new StringBuilder();
                fareText.AppendFormat("{0} ADT {1} CHD ",adt,chd);
                if (chd >= 1)
                {
                    newDetail.FirstChildMinAge = chd1min;
                    newDetail.FirstChildMaxAge = chd1max;
                    fareText.AppendFormat("({0} - {1})", chd1min, chd1max);
                }
                if (chd >= 2)
                {
                    newDetail.SecondChildMinAge = chd2min;
                    newDetail.SecondChildMaxAge = chd2max;
                    fareText.AppendFormat("({0} - {1})", chd2min, chd2max);
                }
                if (chd >= 3)
                {
                    newDetail.ThirdChildMinAge = chd3min;
                    newDetail.ThirdChildMaxAge = chd3max;
                    fareText.AppendFormat("({0} - {1})", chd3min, chd3max);
                }
                if (chd >= 4)
                {
                    newDetail.FourthChildMinAge = chd4min;
                    newDetail.FourthChildMaxAge = chd4max;
                    fareText.AppendFormat("({0} - {1})", chd4min, chd4max);
                }
                db.HotelFareDs.InsertOnSubmit(newDetail);

                
                db.SaveChanges(User.Identity.Name);

               

                return Json(new { id = newDetail.Id, fare = newDetail.Fare.ToMoneyString(), text = fareText.ToString() });
            }
        }

        [HttpPost]
        public ActionResult DeleteDetail(int Id)
        {
            using (var db = this.CreateHotelDataContext())
            {
                db.HotelFareDs.DeleteByIdOnSubmit(Id);
                db.SaveChanges(User.Identity.Name);
            }

            return Json(true);
        }

        [HttpPost]
        public ActionResult UpdateDetail(int Id,decimal fare)
        {
            using (var db = this.CreateHotelDataContext())
            {
                var item = db.HotelFareDs.FirstOrDefault(d => d.Id == Id);
                item.Fare = fare;
                db.SaveChanges(User.Identity.Name);
            }


            return Json(true);
        }

    }
}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelSeason/Create.cshtml
@model List<BilenAdam.Data.HotelData.HotelFareH>
@{
    ViewBag.Title = "Create";

    var marketSelectList = ViewData["MarketList"] as SelectListItem[];
    string[] alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray().Select(s=>s.ToString()).ToArray();

}

<div class="container">
    <div class="card">
        <div class="card-body card-padding">
            <form method="post" class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">Market</label>
                    <div class="col-md-4">
                        @Html.SelectFor(m => m[0].MarketId, marketSelectList, new { @class = "form-control" })
                    </div>
                    <label class="control-label col-md-2">Currency</label>
                    <div class="col-md-4">
                        @Html.CurrencySelectFor(m=>m[0].Currency,new{ @class="form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 table-responsive">


                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.NumberSelect("itemCount", 1, 20, Model.Count(m=>m.Id != 0), false, new {@class= "form-control", @id= "itemCount" })
                                    </th>
                                    <th>
                                        @BilenAdam.Resources.App.SearchNFilters.StartDate
                                    </th>
                                    <th>
                                        @BilenAdam.Resources.App.SearchNFilters.EndDate
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < Model.Count; i++)
                            {
                                    <tr id="item_@i" >
                                        <td>
                                            @Html.HiddenFor(m => m[i].Id)
                                            @Html.HiddenFor(m => m[i].HotelId)
                                            @Html.HiddenFor(m => m[i].HotelSeasonId)
                                            @Html.SelectFor(m => m[i].SeasonCode, new SelectList(alphabet, Model[i].SeasonCode), new { @class = "form-control" })
                                        </td>
                                        <td>
                                            @Html.DateBoxFor(m =>m[i].BeginDate,null,new { @class="form-control begin_date" })
                                        </td>
                                        <td>
                                            @Html.DateBoxFor(m => m[i].EndDate, null, new { @class = "form-control end_date" })
                                        </td>
                                    </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary col-md-offset-1 col-md-10">@BilenAdam.Resources.App.Crud.Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        function showRows()
        {
            var count = parseInt($("#itemCount").val());

            for (var i = 0; i < @Model.Count; i++) {
                if(i < count)
                {
                    $("#item_" + i).show();
                }
                else{
                    $("#item_" + i).hide();
                }
            }
        }

        showRows();
        $("#itemCount").change(function()
        {
            showRows();
        });

        $(".end_date").change(function(){
            var endDate = this;
            $.ajax({
                type:'POST',
                url:'@Url.Action("NextDay")',
                data:{'today':$(endDate).val()},
                success:function(data){
                    var beginDate = data;
                    $(".begin_date", $(endDate).closest('tr').next('tr')).each(function(){
                        $(this).val(beginDate);
                    });
                }
            });
          
        });
    });
</script>

BilenAdam.XITT.Admin.HotelCharter/Views/HotelSeason/Edit.cshtml
@model BilenAdam.Data.HotelData.HotelSeason
@{
}

<div class="container">
    <div class="card">
        <div class="card-body card-padding">
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(m=>m.Id)
                @Html.HiddenFor(m => m.HotelId)
                @Html.ValidationSummary(false)
                
                
                <div class="form-group">
                    @Html.LabelFor(m=>m.Commission, new { @class="control-label" })
                    @Html.PercentSelectFor(m=>m.Commission, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m=>m.Currency, new { @class="control-label" })
                    @Html.CurrencySelectFor(m=>m.Currency, new { @class="form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.HandlingFee, new { @class = "control-label" })
                    @Html.MoneyBoxFor(m => m.HandlingFee, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.TransferFee, new { @class = "control-label" })
                    @Html.MoneyBoxFor(m => m.TransferFee, new { @class = "form-control" })
                </div>
              
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">@BilenAdam.Resources.App.Crud.Save</button>
                </div>
            }
        </div> 
    </div>
</div>

BilenAdam.XITT.Admin.HotelCharter/Views/HotelSeason/Index.cshtml
@model IEnumerable<BilenAdam.Data.HotelData.HotelSeason>

@{
    var hotelData =  ViewData["Hotel"] as BilenAdam.Data.HotelData.Hotel;
}

<div class="container">
    <div class="card">
        <div class="card-body card-padding">
            
          
                <h1>
                    @hotelData.Name / @hotelData.Stars / @hotelData.HotelDestination.Name / Sezonlar

                </h1>
            <a href="@Url.Action("Index","Hotel",new { Id = hotelData.Id })" class="btn btn-default">@BilenAdam.Resources.App.Commands.Back</a>
        </div>
    </div>

    <div class="card">
        <div class="card-body card-padding table-responsive" style="overflow:inherit">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Market
                        </th>
                        <th>
                            @EntityResources.begindate_display
                        </th>
                        <th>
                            @EntityResources.enddate_display
                        </th>
                        <th>

                        </th>
                        <th>

                       
                            <a href="@Url.Action("Create",new { hotelid = Request["hotelid"]  })" class="btn btn-success ">@BilenAdam.Resources.App.Crud.New</a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr>
                            <td>
                                @item.HotelMarket.Name
                            </td>
                            <td>
                                @Html.DateDisplay(item.BeginDate)
                            </td>
                            <td>
                                @Html.DateDisplay(item.EndDate)
                            </td>
                           
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Tanimlar <span class="caret"></span>
                                        @if (item.HotelFareHs.Count() > 0)
                                        {
                                            <i class="fa fa-check text-success"></i>
                                        }
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="@Url.Action("Index","HotelFare",new { hotelSeasonId = item.Id  })" >Fiyatlar
                                                @if (item.HotelFareHs.Count() > 0)
                                                {
                                                    <i class="fa fa-check text-success"></i>
                                                }
                                            </a></li>
                                        <li>
                                            <a href="@Url.Action("Index","HotelSPO",new { hotelSeasonId = item.Id  })">
                                                SPO
                                                @if (item.HotelFareHs.Count(f=>f.IsSPOEnabled == true) > 0)
                                                {
                                                    <i class="fa fa-check text-success"></i>
                                                }
                                            </a>
                                        </li>
                                        <li><a href="@Url.Action("Index","HotelPromotion",new { hotelSeasonId = item.Id  })" >Promosyonlar
                                                @if (item.HotelPromotions.Count() > 0)
                                                {
                                                    <i class="fa fa-check text-success"></i>
                                                }
                                            </a></li>

                                        <li>
                                            <a href="@Url.Action("Index","HotelSeasonChildrenFee",new { hotelSeasonId = item.Id, hotelId = item.HotelId  })">
                                                Children Transfer and Handling Fees
                                                @if (item.HotelSeasonChildrenFees.Count() > 0)
                                                {
                                                    <i class="fa fa-check text-success"></i>
                                                }
                                            </a>
                                        </li>
                                       
                                        <li><a href="@Url.Action("Create",new {hotelid = item.HotelId, Id = item.Id  })">Tarih Araliklari <i class="fa fa-check text-success"></i></a></li>
                                      
                                    </ul>
                                </div>
                                
                            </td>
                        
                            <td>
                                <a href="@Url.Action("Edit",new { hotelid = item.HotelId, id = item.Id  })" class="btn btn-default">@BilenAdam.Resources.App.Crud.Edit</a>
                           
                                <a href="@Url.Action("Delete",new { hotelid = item.HotelId, id = item.Id  })" class="btn btn-danger">@BilenAdam.Resources.App.Crud.Delete</a>
                            </td>
                        </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>