BilenAdam.XITT.Admin.HotelCharter/Controllers/HotelRoomTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using BilenAdam.Data.HotelData;
using BilenAdam.Utilities.Paging;

namespace BilenAdam.XITT.Admin.HotelCharter.Controllers
{
    public class HotelRoomTypeController : Controller
    {

        public ActionResult Index()
        {
            using (var db = this.CreateHotelDataContext())
            {
                var data = db.HotelRoomTypes.AsQueryable();

                if (!string.IsNullOrWhiteSpace(Request["name"]))
                    data = data.Where(i => i.RoomType.Contains(Request["name"]));

                var model = data.OrderBy(i=>i.RoomType).ToPagedList<HotelRoomType>(Request);
                return View(model);
            }
        }







        [HttpPost]
        public ActionResult Create(BilenAdam.Data.HotelData.HotelRoomType model)
        {
            try
            {
                using (var db = this.CreateHotelDataContext())
                {

                    db.HotelRoomTypes.InsertOnSubmit(model);
                    db.SaveChanges(User.Identity.Name);
                }

                return this.Redirect2Action(s => s.Index());
            }
            catch (Exception exc)
            {
                ModelState.AddModelError(string.Empty, exc.Message);
            }

            return this.Redirect2Action(s => s.Index());
        }




        [HttpPost]
        public ActionResult Edit(BilenAdam.Data.HotelData.HotelRoomType model)
        {
            if (ModelState.IsValid)
            {
                using (var db = this.CreateHotelDataContext())
                {


                    var item = db.HotelRoomTypes.FirstOrDefault(c => c.Id == model.Id);

                    if (item == null)
                        return HttpNotFound();

                    item.UpdateFrom(model, "xRes");

                    db.SaveChanges(User.Identity.Name);

                }

            }
            return this.Redirect2Action(s => s.Index());
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = this.CreateHotelDataContext())
                {

                    db.HotelRoomTypes.DeleteByIdOnSubmit(id);
                    db.SaveChanges(User.Identity.Name);
                }


            }
            catch (Exception exc)
            {
                ModelState.AddModelError(null, exc.Message);
            }
            return this.Redirect2Action(s => s.Index());
        }
    }
}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelRoomType/CreatePartial.cshtml
@model  BilenAdam.Data.HotelData.HotelRoomType




@using (Html.BeginForm("Create", "HotelRoomType", FormMethod.Post, new { @class = "form-inline" }))
{





    <div class="form-group">
        <label>@BilenAdam.Resources.App.Crud.New</label>

        @Html.TextBoxFor(m => m.RoomType, new { @class = "form-control" })




        <!-- Button trigger modal -->
        <button type="button" class="btn" data-toggle="modal" data-target="#myModal">
            <i class="fa fa-globe"></i>
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                    </div>
                    <div class="modal-body">

                        @Html.Partial("ResourceEditorPartial", PropertyResourceEditorModelUtils.Create(Model, m => m.RoomType, BilenAdam.Data.HotelData.Resources.EntityResources.roomtype_display))
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    </div>







            <button type="submit" class="btn btn-success">@BilenAdam.Resources.App.Crud.Save</button>


}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelRoomType/EditPartial.cshtml
@model  BilenAdam.Data.HotelData.HotelRoomType

@{
    ViewBag.Title = "Update";
}


@using (Html.BeginForm("Edit", "HotelRoomType", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)


    @Html.HiddenFor(o => o.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.RoomType, new { @class = "col-sm-3 control-label" })
        <div class="col-sm-9">
            @Html.TextBoxFor(m => m.RoomType, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">

        @Html.Partial("ResourceEditorPartial", PropertyResourceEditorModelUtils.Create(Model, m => m.RoomType, BilenAdam.Data.HotelData.Resources.EntityResources.roomtype_display))
    </div>
    <div class="form-group">


    </div>
    <div class="btn-group btn-group-justified">
        <div class="btn-group">
            <button type="submit" class="btn btn-primary">@BilenAdam.Resources.App.Crud.Save</button>
        </div>


    </div>

}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelRoomType/Index.cshtml
@model PagedList<HotelRoomType>


@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="card">
        <div class="card-body card-padding">

            <form method="get" class="form-inline">

                <div class="form-group">

                    @Html.SearchFormTextInput("name")
                </div>

                <button class="btn btn-primary" type="submit">@BilenAdam.Resources.App.SearchNFilters.Search</button>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-body card-padding">


            <div class="row">
                @Html.Partial("CreatePartial", new BilenAdam.Data.HotelData.HotelRoomType())
            </div>
            <div class="row table-responsive">
                <table class="table">
                    <tr>
                        <th>
                            @EntityResources.id_display
                        </th>

                        <th>
                            @EntityResources.name_display
                        </th>

                        <th colspan="2">

                        </th>
                    </tr>

                    @foreach (var item in Model)
            {
                        <tbody>
                            <tr>
                                <td>
                                    @item.Id
                                </td>


                                <td>
                                    @item.RoomType
                                </td>
                                <td>
                                    <button type="button" class="btn" data-toggle="modal" data-target="#myModal_@item.Id">
                                        @BilenAdam.Resources.App.Crud.Edit
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="myModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                                                </div>
                                                <div class="modal-body">

                                                    @Html.Partial("EditPartial", item)
                                                </div>
                                                <div class="modal-footer">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="@Url.Action("Delete", new { Id = item.Id })" class="btn btn-link">
                                        @BilenAdam.Resources.App.Crud.Delete
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    }
                    <tfoot>
                        <tr>
                            <td colspan="4">
                                @Html.Pager(Model)
                            </td>
                        </tr>
                    </tfoot>

                </table>
            </div>
        </div>
    </div>
</div>