BilenAdam.XITT.Admin.HotelCharter/Controllers/HotelCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using BilenAdam.Data.HotelData;
using BilenAdam.Utilities.Paging;

using System.Data.Linq;
using BilenAdam.XITT.Admin.HotelCharter.Models;

namespace BilenAdam.XITT.Admin.HotelCharter.Controllers
{
    public class HotelCategoryController : Controller
    {
        public ActionResult Index(int pageIndex = 1, int pageSize = 10)
        {
           
         
            using (var db = this.CreateHotelDataContext())
            {
                ////  DataLoadOptions dlo = new DataLoadOptions();
                //  dlo.LoadWith<Contact>(c=>c.CharterProRataContracts)
                //db.LoadOptions = dlo;
                var data = db.HotelCategories.AsQueryable();

                var model = data.ToPagedList<HotelCategory>(pageIndex, pageSize);
                return View(model);
            }
        }

    

        [HttpPost]
        public ActionResult Create(BilenAdam.Data.HotelData.HotelCategory model)
        {
            
            if (ModelState.IsValid)
            {

                try
                {
                    using (var db = this.CreateHotelDataContext())
                    {
                       

                        PropertyResourceEditorModelUtils.FillResources(model, m => m.Name, Request);
                        db.HotelCategories.InsertOnSubmit(model);
                        db.SaveChanges(User.Identity.Name);
                    }

                    return this.Redirect2Action(s => s.Index(1, 10));
                }
                catch (Exception exc)
                {
                    ModelState.AddModelError(string.Empty, exc.Message);
                }
            }
            return this.Redirect2Action(s => s.Index(1, 10));
        }

       


     

        [HttpPost]
        public ActionResult Edit(BilenAdam.Data.HotelData.HotelCategory model)
        {
            if(ModelState.IsValid)
            {
                using (var db = this.CreateHotelDataContext())
                {
                  

                    var item = db.HotelCategories.FirstOrDefault(c => c.Id == model.Id);

                    if (item == null)
                        return HttpNotFound();

                    item.UpdateFrom(model,"xRes");
                    PropertyResourceEditorModelUtils.FillResources(item, m => m.Name, Request);
                    db.SaveChanges(User.Identity.Name);
                   

                }
            }

            return this.Redirect2Action(s => s.Index(1, 10));
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = this.CreateHotelDataContext())
                {
                    db.HotelCategories.DeleteByIdOnSubmit(id);
                    db.SaveChanges(User.Identity.Name);
                    
                }


            }
            catch (Exception exc)
            {
                ModelState.AddModelError(null, exc.Message);
            }
            return this.Redirect2Action(s => s.Index(1, 10));
        }

       
    }
}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelCategory/CreatePartial.cshtml
@model  BilenAdam.Data.HotelData.HotelCategory




    @using (Html.BeginForm("Create", "HotelCategory", FormMethod.Post, new { @class = "form-inline" }))
    {
       
        <div class="form-group">
            <label>@BilenAdam.Resources.App.Crud.New</label>
        </div>
       


        <div class="form-group">
          
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
          
       


               
        
            </div>
      

       <div class="form-group">
           <!-- Button trigger modal -->
           <button type="button" class="btn" data-toggle="modal" data-target="#myModal">
               <i class="fa fa-globe"></i> 
           </button>

           <!-- Modal -->
           <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
               <div class="modal-dialog" role="document">
                   <div class="modal-content">
                       <div class="modal-header">
                           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                       </div>
                       <div class="modal-body">

                           @Html.Partial("ResourceEditorPartial", PropertyResourceEditorModelUtils.Create(Model, m => m.Name, BilenAdam.Data.HotelData.Resources.EntityResources.name_display))
                       </div>
                       <div class="modal-footer">
                           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                       </div>
                   </div>
               </div>
           </div>
       </div>
          
        

        <button type="submit" class="btn btn-success">@BilenAdam.Resources.App.Crud.Save</button>

 
    }

BilenAdam.XITT.Admin.HotelCharter/Views/HotelCategory/EditPartial.cshtml
@model  BilenAdam.Data.HotelData.HotelCategory

@{
    ViewBag.Title = "Update";
}


@using (Html.BeginForm("Edit", "HotelCategory", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)



    @Html.HiddenFor(o => o.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-3 control-label" })
        <div class="col-sm-9">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">

        @Html.Partial("ResourceEditorPartial", PropertyResourceEditorModelUtils.Create(Model, m => m.Name, BilenAdam.Data.HotelData.Resources.EntityResources.name_display))
    </div>
    <div class="btn-group btn-group-justified">
        <div class="btn-group">
            <button type="submit" class="btn btn-primary">@BilenAdam.Resources.App.Crud.Save</button>
        </div>


    </div>


}

BilenAdam.XITT.Admin.HotelCharter/Views/HotelCategory/Index.cshtml
@model PagedList<HotelCategory>


@{
    ViewBag.Title = "Index"; 
}

<div class="card container">
    <div class="card-body card-padding">
        <div class="row">
            @Html.Partial("CreatePartial", new HotelCategory())
        </div>
        <div class="row table-responsive">
            <table class="table">
                <tr>
                    <th>
                        @EntityResources.id_display
                    </th>

                    <th>
                        @EntityResources.name_display
                    </th>

                    <th colspan="2">

                    </th>
                </tr>

                @foreach (var item in Model)
            {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>


                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn" data-toggle="modal" data-target="#myModal_@item.Id">
                                    @BilenAdam.Resources.App.Crud.Edit
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" id="myModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                                            </div>
                                            <div class="modal-body">

                                                @Html.Partial("EditPartial", item)
                                            </div>
                                            <div class="modal-footer">

                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </td>
                            <td>
                                <a href="@Url.Action("Delete", new { Id = item.Id })" class="btn btn-link">
                                    @BilenAdam.Resources.App.Crud.Delete
                                </a>
                            </td>
                        </tr>
                    </tbody>
            }
                <tfoot>
                    <tr>
                        <td colspan="4">
                            @Html.Pager(Model)
                        </td>
                    </tr>
                </tfoot>

            </table>
        </div>
    </div>
</div>